### ISSUE TITLE
npm WARN deprecated css-list@0.1.3: Deprecated.

### ISSUE THREAD

**Issue by xet7** [exherb/dashing#1]
Hi,
I'm using golang 1.5.2 and node version 5.2.0.

I generated dashboard and I'm in install phase with command "npm install" and it gives this error:

```
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN install Couldn't install optional dependency: Unsupported
```

And at the end of install, it gives these errors:

```
npm WARN EPEERINVALID vue-loader@7.2.0 requires a peer of babel-runtime@^5.8.0 b
ut none was installed.
npm WARN EPACKAGEJSON dashboard@0.1.0 No description
npm WARN EPACKAGEJSON dashboard@0.1.0 No repository field.
```

I tried to fix those errors, but I did not get it working yet. Could you try to fix it?

Best Regards,
xet7

**Comment by xet7** [comment]
This issue may more likely belong to your dashing-cli repo, I'm not sure.

**Comment by exherb** [comment]
@xet7 this may solve your issue https://github.com/laravel/elixir/issues/331#issuecomment-156613940
