### ISSUE TITLE
Responsive layout?

### ISSUE THREAD

**Issue by xet7** [exherb/dashing#2]
Hi,
is it possible to have responsive layout, so that dashboard resizes to screen width etc?
There is an issue on this project about gridster to gridstack conversion on this dashing version:
https://github.com/Shopify/dashing/issues/11
So newest fork commit of gridstack is here:
https://github.com/yulisys/gridstack.js
Is there some similar possibility on your exherb/dashing using vuejs ?
I'm currently trying to figure out how to get gridstack working with dashing-go that currently uses gridster, but at some point I'll try to port my current app from dashing-go to exherb/dashing.
Your dashing version is much cleaner when you use native golang http and httprouter instead of dashing-go martini's dependency injection.

**Comment by xet7** [comment]
When I read your demo app.js code it seems that you use gridster, is it possible that you change it to gridstack using responsive layout?

**Comment by exherb** [comment]
I will try to make it possible, or feel free to send a pull request.

**Comment by xet7** [comment]
Ok, if I get it working myself I'll make a pull request.

**Comment by xet7** [comment]
@exherb 
Currently on my app previous dashing-go version I do scaling to fullscreen with following code to get 4 columns x 2 rows table scaled to fullscreen. Is it possible to do something similar in exherb/dashing version? Where is the correct place to make these changes? I tried to add this code, but it produced broken layout. I will try again later.

## Original scaling code

https://github.com/Shopify/dashing/issues/608

## Widget Size Scaling: `public/index.html`

``` javascript
<script type='text/javascript'>
$(function() {
  // These settings override the defaults set in application.coffee. You can do this on a per dashboard basis.
  Dashing.widget_base_dimensions = [$( window ).width()/4.2, $( window ).height()/2.2];
  Dashing.widget_margins = [5, 5];
  Dashing.numColumns = 4;
  });
</script>
```

## Font Size Scaling, `public/css/application.css`

``` css
@font-face {
  font-size: 8vw;
}
.widget-meter {
  font-size: 4vw;
}
h1 {
  font-size: 3vw;
}
h3 {
  font-size: 4vw;
}
```

**Comment by xet7** [comment]
Both your dashing version and dashing-go use gridster.

**Comment by xet7** [comment]
On your dashing when there's info how many columns are at dashboad, dashing could calculate correct sizing of widgets etc with javascript.
